# Numpy

In [2]:
import numpy as np

In [18]:
x = np.array([1,2,3,4,5,6,7,8,9])
type(x)

numpy.ndarray

In [13]:
print(x.dtype)
print(x.shape)

int32
(6,)


In [23]:
y = x.reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
y.ravel() # Flattens the array into a row 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
y.reshape(9, -1) #columns can be in any number but row should be one

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [34]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.ones((3,3)).dtype

dtype('float64')

In [36]:
np.ones((4, 3), dtype = 'int64')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [38]:
np.arange(0, 10, 2).reshape(-1, 1).ravel() # 2 is increment step

array([0, 2, 4, 6, 8])

In [63]:
print(np.random.rand(2))
print(np.random.rand(2,2))
#np.random.seed(0)
print(np.random.random((3, 3)))

[0.60783067 0.32504723]
[[0.03842543 0.63427406]
 [0.95894927 0.65279032]]
[[0.63505887 0.99529957 0.58185033]
 [0.41436859 0.4746975  0.6235101 ]
 [0.33800761 0.67475232 0.31720174]]


In [4]:
np.random.randint(0, 50, (3, 4), dtype='int32') # (4, 3) is shape with values between 0-50

array([[41,  9, 39, 32],
       [ 3, 39, 41, 14],
       [45, 20, 14, 46]])

In [75]:
np.linspace(0, 100, 11) # Picking 11 equally distributes values from 0-100 inclusive

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [72]:
np.logspace(0, 15, endpoint=False)

array([1.00000000e+00, 1.99526231e+00, 3.98107171e+00, 7.94328235e+00,
       1.58489319e+01, 3.16227766e+01, 6.30957344e+01, 1.25892541e+02,
       2.51188643e+02, 5.01187234e+02, 1.00000000e+03, 1.99526231e+03,
       3.98107171e+03, 7.94328235e+03, 1.58489319e+04, 3.16227766e+04,
       6.30957344e+04, 1.25892541e+05, 2.51188643e+05, 5.01187234e+05,
       1.00000000e+06, 1.99526231e+06, 3.98107171e+06, 7.94328235e+06,
       1.58489319e+07, 3.16227766e+07, 6.30957344e+07, 1.25892541e+08,
       2.51188643e+08, 5.01187234e+08, 1.00000000e+09, 1.99526231e+09,
       3.98107171e+09, 7.94328235e+09, 1.58489319e+10, 3.16227766e+10,
       6.30957344e+10, 1.25892541e+11, 2.51188643e+11, 5.01187234e+11,
       1.00000000e+12, 1.99526231e+12, 3.98107171e+12, 7.94328235e+12,
       1.58489319e+13, 3.16227766e+13, 6.30957344e+13, 1.25892541e+14,
       2.51188643e+14, 5.01187234e+14])

In [91]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
%timeit np.exp(x) # Average Time taken for execution

2 µs ± 233 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [98]:
np.max(x)
np.min(x)
np.average(x)

5.0

In [97]:
np.sin(x)
np.cos(x)
np.tan(x)
np.tanh(x)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ,
       0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [115]:
def avg(ls):
   # print(sum(ls)/len(ls))
    s = 0
    for i in range(len(ls)):
        s += ls[i]
    avg = s/(i+1)

ls = [20, 32, 13, 341, 142, 412]
x = np.array(ls)
%timeit avg(ls)

1.59 µs ± 83.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [118]:
%timeit np.average(x)

13.6 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [119]:
2**x

array([1048576,       0,    8192,       0,       0,       0], dtype=int32)

In [122]:
x[::2]

array([ 20,  13, 142])

In [131]:
x = x.reshape(2,3)
print(x)
x[1, 1:]

[[ 20  32  13]
 [341 142 412]]


array([142, 412])